export const RECEIVE_NEXT_SESSIONS_TODAY = 'RECEIVE_NEXT_SESSIONS_TODAY';
export const RECEIVE_SESSION_SCHEDULE = 'RECEIVE_SESSION_SCHEDULE';
export const SET_USER_ID = 'SET_USER_ID';
export const RECEIVE_THERAPYES = 'RECEIVE_THERAPYES';
export const CHANGE_SELECTED_DAY = 'CHANGE_SELECTED_DAY';
export const SAVE_SESSION = 'SAVE_SESSION';
