export const RECEIVE_SESSION = 'RECEIVE_SESSION';
export const RECEIVE_SESSION_THERAPISTS = 'RECEIVE_SESSION_THERAPISTS';
export const RECEIVE_SESSION_THERAPIES = 'RECEIVE_SESSION_THERAPIES';
export const RECEIVE_ALL_THERAPIES = 'RECEIVE_ALL_THERAPIES';
export const RECEIVE_SESSION_TIME_SCHEDULE = 'RECEIVE_SESSION_TIME_SCHEDULE';
export const SET_THERAPY_TYPE = 'SET_THERAPY_TYPE';
