
export const APPOINTMENT_RECEIVED = 'APPOINTMENT_RECEIVED';
export const TREATMENTS_RECEIVED = 'TREATMENTS_RECEIVED';
export const DOCTORS_RECEIVED = 'DOCTORS_RECEIVED';
export const DOCTORS_SCHEDULES_RECEIVED = 'DOCTORS_SCHEDULES_RECEIVED';
export const TREATMENTS_FILTERED = 'TREATMENTS_FILTERED';
export const SET_DOCTOR = 'SET_DOCTOR';
export const SET_TREATMENT = 'SET_TREATMENT';
export const SET_DISABLE_DATES = 'SET_DISABLE_DATES';
export const SET_DISABLE_DATES_TIMES = 'SET_DISABLE_DATES_TIMES';

// OLD
/*
export const RECEIVE_SESSION = 'RECEIVE_SESSION';
export const RECEIVE_SESSION_THERAPISTS = 'RECEIVE_SESSION_THERAPISTS';
export const RECEIVE_SESSION_THERAPIES = 'RECEIVE_SESSION_THERAPIES';
export const RECEIVE_ALL_THERAPIES = 'RECEIVE_ALL_THERAPIES';
export const RECEIVE_SESSION_TIME_SCHEDULE = 'RECEIVE_SESSION_TIME_SCHEDULE';
export const SET_THERAPY_TYPE = 'SET_THERAPY_TYPE';
export const RECEIVE_DISABLE_DAYS = 'RECEIVE_DISABLE_DAYS';
export const RECEIVE_DISABLE_TIMES = 'RECEIVE_DISABLE_TIMES';
export const RECEIVE_DISABLE_THERAPISTS = 'RECEIVE_DISABLE_THERAPISTS';
export const SET_INIT_DATE = 'SET_INIT_DATE';
export const SET_DATE = 'SET_DATE';
export const SET_TIME = 'SET_TIME';
export const SET_THERAPI = 'SET_THERAPI';
export const SET_ADDRESS = 'SET_ADDRESS';
*/
