
export const APPOINTMENT_RECEIVED = 'APPOINTMENT_RECEIVED';
export const TREATMENTS_RECEIVED = 'TREATMENTS_RECEIVED';
export const DOCTORS_RECEIVED = 'DOCTORS_RECEIVED';
export const DOCTORS_SCHEDULES_RECEIVED = 'DOCTORS_SCHEDULES_RECEIVED';
export const TREATMENTS_FILTERED = 'TREATMENTS_FILTERED';
export const SET_DOCTOR = 'SET_DOCTOR';
export const SET_TREATMENT = 'SET_TREATMENT';
export const SET_DISABLE_DATES = 'SET_DISABLE_DATES';
export const SET_DISABLE_DATES_TIMES = 'SET_DISABLE_DATES_TIMES';
export const SET_DISABLE_TIMES = 'SET_DISABLE_TIMES';
export const SET_DATE_SELECTED = 'SET_DATE_SELECTED';
export const SET_TIME_SELECTED = 'SET_TIME_SELECTED';
export const SET_DOCTOR_SCHEDULE = 'SET_DOCTOR_SCHEDULE';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_DOCTOR_ICON_STATUS = 'SET_DOCTOR_ICON_STATUS';
export const SET_APPOINTMENT_ICON_STATUS = 'SET_APPOINTMENT_ICON_STATUS';
export const SET_LOCATION_ICON_STATUS = 'SET_LOCATION_ICON_STATUS';
export const READY_TO_SAVE = 'READY_TO_SAVE';

