export const RECEIVE_TODAY_SESSIONS = 'RECEIVE_TODAY_SESSIONS';
export const RECEIVE_SESSION_TIME_SCHEDULE = 'RECEIVE_SESSION_TIME_SCHEDULE';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_SELECTED_DATA = 'SET_SELECTED_DAY';
export const RECEIVE_THERAPYES = 'RECEIVE_THERAPYES';
export const SET_INIT_DATE = 'SET_INIT_DATE';
